apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      pod-label: flask-pod
  template: # pod defination
    metadata: 
      name: my-pod
      labels:
        app: backend
        pod-label: flask-pod
    spec:
      # volumes:
      # - name: cert-volume
      #   secret:
      #     secretName: "secret-nginx-cert" 
      containers:
      - name: flask-container
        image: rapidfort/flaskapp:latest
        ports:
        - containerPort: 8555
        # - containerPort: 8556
        # volumeMounts:
        # - mountPath: "/certs"
        #   name: cert-volume 
        volumeMounts:
          - name: flask-pvc-storage
            mountPath: /application
        env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: flask-secret # secretName created
              key: author
        command: ["/bin/sh", "-c"]
        args: ["ls; pip install mysql-connector-python==8.0.29; echo $(SECRET_USERNAME);python app_simple.py"]
        
      volumes:
        - name: flask-pvc-storage
          persistentVolumeClaim:
            claimName:  flask-pvc