apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv1
  labels:
    name: my-pv1
spec:
  storageClassName: mystorageclass
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/supersaiyan/Documents/Dan/k3s_test/my_pv"