apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplicacontroller1
  labels:
    app: my-simple-replica
spec:
  replicas: 3
  selector: # replica selector
    pod-label: simple-pod
  template: # pod defination
    metadata: 
      name: mypod
      labels:
        app: backend
        pod-label: simple-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2