apiVersion: v1
kind: Pod
metadata:
  name: command-demo-pod
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: debian
    command: ["/bin/sh", "-c"]
    args:
    - while true; do
        echo -en '\n';
        printenv MY_NODE_NAME MY_VAR;
        sleep 10;
      done;
    env:
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath:
            spec.nodeName
    - name: MY_VAR
      value: "He He"
  restartPolicy: OnFailure