apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  labels:
    type: local
spec:
  storageClassName: nginx-pv-class
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/supersaiyan/Documents/Dan/k3s_test/simple_pv_nginx/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  storageClassName: nginx-pv-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
